version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sista
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sista
      # use host.docker.internal so container can reach a host-registered LMStudio service
      LMSTUDIO_URL: ${LMSTUDIO_URL:-http://host.docker.internal:1234}
    depends_on:
      - db
    ports:
      # publish backend on host port 8030 per user request (container still listens on 8000)
      - "8030:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: sh -c "pnpm install && pnpm dev"

volumes:
  db-data:
